!!python/object:argparse.Namespace
SuperNetSetting:
- - 4
  - 8
  - 12
  - 16
- - 4
  - 8
  - 12
  - 16
- - 4
  - 8
  - 12
  - 16
- - 4
  - 8
  - 12
  - 16
- - 4
  - 8
  - 12
  - 16
- - 4
  - 8
  - 12
  - 16
- - 4
  - 8
  - 12
  - 16
- - 4
  - 8
  - 12
  - 16
  - 20
  - 24
  - 28
  - 32
- - 4
  - 8
  - 12
  - 16
  - 20
  - 24
  - 28
  - 32
- - 4
  - 8
  - 12
  - 16
  - 20
  - 24
  - 28
  - 32
- - 4
  - 8
  - 12
  - 16
  - 20
  - 24
  - 28
  - 32
- - 4
  - 8
  - 12
  - 16
  - 20
  - 24
  - 28
  - 32
- - 4
  - 8
  - 12
  - 16
  - 20
  - 24
  - 28
  - 32
- - 4
  - 8
  - 12
  - 16
  - 20
  - 24
  - 28
  - 32
  - 36
  - 40
  - 44
  - 48
  - 52
  - 56
  - 60
  - 64
- - 4
  - 8
  - 12
  - 16
  - 20
  - 24
  - 28
  - 32
  - 36
  - 40
  - 44
  - 48
  - 52
  - 56
  - 60
  - 64
- - 4
  - 8
  - 12
  - 16
  - 20
  - 24
  - 28
  - 32
  - 36
  - 40
  - 44
  - 48
  - 52
  - 56
  - 60
  - 64
- - 4
  - 8
  - 12
  - 16
  - 20
  - 24
  - 28
  - 32
  - 36
  - 40
  - 44
  - 48
  - 52
  - 56
  - 60
  - 64
- - 4
  - 8
  - 12
  - 16
  - 20
  - 24
  - 28
  - 32
  - 36
  - 40
  - 44
  - 48
  - 52
  - 56
  - 60
  - 64
- - 4
  - 8
  - 12
  - 16
  - 20
  - 24
  - 28
  - 32
  - 36
  - 40
  - 44
  - 48
  - 52
  - 56
  - 60
  - 64
- - 4
  - 8
  - 12
  - 16
  - 20
  - 24
  - 28
  - 32
  - 36
  - 40
  - 44
  - 48
  - 52
  - 56
  - 60
  - 64
autoaug: false
batch_size: 128
classes: 10
config: configs/meta.yml
cutout: 0
dataset: cifar10
distill: false
epochs: 300
exp_name: resnet50_autoaug_08M_29D_09H_0359
finetune: false
gpu: 0
grad_clip: 5
label_smooth: 0.1
learning_rate: 0.1
local_rank: 0
mixup: false
mixup_alpha: 1.0
model_type: resnet50
momentum: 0.9
num_workers: 3
report_freq: 100
resume: ''
sandwich_N: 3
save_dir: resnet50_autoaug
seed: 0
track_file: Track1_200_archs.json
weight_decay: 0.0005
